import type { FileCategory } from './types.js';

const GENERATED_MARKERS = [
  '@generated',
  'AUTO-GENERATED',
  'Code generated by',
  'DO NOT EDIT',
] as const;

function hasGeneratedHeader(content: string): boolean {
  const head = content.slice(0, 800);
  return GENERATED_MARKERS.some((marker) => head.includes(marker));
}

function isTestPath(normalizedPath: string): boolean {
  if (/\.(test|spec)\.[tj]sx?$/.test(normalizedPath)) {
    return true;
  }
  if (normalizedPath.includes('/__tests__/')) {
    return true;
  }
  return false;
}

function isSeedPath(normalizedPath: string): boolean {
  return (
    normalizedPath.includes('/seeds/') ||
    /\/seed-[^/]+\.[tj]sx?$/.test(normalizedPath) ||
    normalizedPath.startsWith('scripts/seed-')
  );
}

function isFixturePath(normalizedPath: string): boolean {
  return (
    normalizedPath.includes('/fixtures/') ||
    normalizedPath.includes('/__fixtures__/') ||
    normalizedPath.includes('/__mocks__/') ||
    normalizedPath.includes('/test-flows/')
  );
}

/** Classify a TS/TSX file for threshold policy (first match wins). */
export function classifyFile(normalizedPath: string, content: string): FileCategory {
  if (hasGeneratedHeader(content)) {
    return 'generated';
  }
  if (isFixturePath(normalizedPath)) {
    return 'fixture';
  }
  if (isTestPath(normalizedPath)) {
    return 'test';
  }
  if (isSeedPath(normalizedPath)) {
    return 'seed';
  }
  return 'production';
}
