/**
 * Every relative link, and every inline path that names a repository file, in a
 * document the public repository ships resolves inside it. Neither is compiled,
 * typechecked or imported.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, posix } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { ownerOf, survivesCoreCut } from './ownershipLookup.js';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '../../../..');

function publicFiles(): Set<string> {
  const tracked = execFileSync('git', ['ls-files'], {
    cwd: REPO_ROOT,
    encoding: 'utf-8',
    maxBuffer: 64 * 1024 * 1024,
  })
    .split('\n')
    .filter((line) => line.trim() !== '');
  return new Set(
    tracked.filter((file) => {
      const owner = ownerOf(file);
      return owner !== undefined && survivesCoreCut(owner.owner);
    }),
  );
}

interface Link {
  from: string;
  href: string;
  target: string;
}

/** Relative links only: an external URL is somebody else's to keep working. */
function relativeLinks(file: string, source: string): Link[] {
  const links: Link[] = [];
  for (const match of source.matchAll(/\[[^\]]*\]\(([^)\s]+)\)/g)) {
    const href = match[1];
    if (href === undefined) continue;
    if (/^(https?:|mailto:|#|<)/.test(href)) continue;
    const withoutAnchor = href.split('#')[0];
    if (withoutAnchor === undefined || withoutAnchor === '') continue;
    links.push({
      from: file,
      href,
      target: posix.normalize(posix.join(posix.dirname(file), withoutAnchor)).replace(/\/$/, ''),
    });
  }
  return links;
}

describe('links in the documents the public repository ships', () => {
  const shipped = publicFiles();
  const markdown = [...shipped].filter(
    (file) => file.endsWith('.md') && existsSync(join(REPO_ROOT, file)),
  );

  it('has public markdown to check', () => {
    // A resolver that found nothing would pass every assertion below.
    expect(markdown.length).toBeGreaterThan(20);
  });

  it('resolves every relative link to something the public repository also ships', () => {
    const broken: string[] = [];
    let checked = 0;
    for (const file of markdown) {
      for (const link of relativeLinks(file, readFileSync(join(REPO_ROOT, file), 'utf-8'))) {
        checked += 1;
        if (shipped.has(link.target)) continue;
        // A link to a directory resolves if anything public lives under it.
        if ([...shipped].some((candidate) => candidate.startsWith(`${link.target}/`))) continue;
        broken.push(`${link.from} → ${link.href}`);
      }
    }
    expect(checked).toBeGreaterThan(20);
    expect(broken).toEqual([]);
  });
});

/** Inline `code` spans that name a repository file: a top-level directory and an extension. */
function inlinePaths(source: string): string[] {
  const found: string[] = [];
  for (const match of source.matchAll(/`([^`\n]+)`/g)) {
    const text = match[1];
    if (text === undefined) continue;
    if (!/^(apps|packages|scripts|docs)\/[A-Za-z0-9._/()[\]-]+\.[a-z]{2,4}$/.test(text)) continue;
    // The earlier plan archive is deliberately unpublished and `docs/plans/README.md`
    // says so, which makes a reference into it a pointer rather than a broken path.
    if (text.startsWith('docs/plans/aflow/')) continue;
    found.push(text);
  }
  return found;
}

describe('inline paths in the documents the public repository ships', () => {
  const shipped = publicFiles();
  // A generated document is regenerated by the cut for its own tree, so its
  // monorepo content is not what ships; its generator owns its correctness.
  const markdown = [...shipped].filter(
    (file) =>
      file.endsWith('.md') &&
      existsSync(join(REPO_ROOT, file)) &&
      !readFileSync(join(REPO_ROOT, file), 'utf-8').startsWith('<!-- GENERATED FILE'),
  );

  it('names files that are there', () => {
    const missing: string[] = [];
    let checked = 0;
    for (const file of markdown) {
      for (const path of inlinePaths(readFileSync(join(REPO_ROOT, file), 'utf-8'))) {
        checked += 1;
        if (shipped.has(path)) continue;
        missing.push(`${file} → ${path}`);
      }
    }
    expect(checked).toBeGreaterThan(10);
    expect(missing).toEqual([]);
  });
});
