/**
 * The seed world, built so that every decision row has a case that reaches it.
 *
 * Dates are derived from one anchor rather than written out, because a refund
 * is `within_window` or `overdue` by arithmetic against an approved deadline —
 * write the dates as literals and the scenario means something different the
 * week after it was authored. Tests pin the anchor; a live space re-seeds when
 * it has drifted past a deadline it was meant to sit inside.
 */

export const CS_DESK_CLOCK_MS = Date.parse('2026-09-10T09:00:00.000Z');

const day = 86_400_000;
const hour = 3_600_000;
const ago = (days: number): string => new Date(CS_DESK_CLOCK_MS - days * day).toISOString();
const hoursAgo = (hours: number): string => new Date(CS_DESK_CLOCK_MS - hours * hour).toISOString();
const ahead = (days: number): string => new Date(CS_DESK_CLOCK_MS + days * day).toISOString();

const SAR = 'SAR';
const AED = 'AED';
const sar = (amount: number) => ({ amount, currency: SAR });
const aed = (amount: number) => ({ amount, currency: AED });

export const CS_DESK_PERSONAS = [
  {
    personaId: 'cus_sa_amal',
    label: 'Amal — Riyadh',
    brief:
      'Four orders, all in Saudi Arabia. One refund is pending inside its approved window, one is pending well past it and policy requires investigation, one settled entirely against the payment plan, and one order has no refund at all.',
  },
  {
    personaId: 'cus_sa_faisal',
    label: 'Faisal — Jeddah',
    brief:
      'Declined checkouts across four codes — a final credit decision, an issuer timeout below and above its escalation threshold, and one code with no approved mapping. Also several payment problems: a captured payment that never reached the plan, an authorisation hold, a duplicate capture already being corrected and another that is not, a reversal, and one payment whose ledger source is lagging.',
  },
  {
    personaId: 'cus_ae_rana',
    label: 'Rana — Dubai',
    brief:
      'UAE account. A merchant has blocked one refund and a dispute claim already exists for it; a second merchant-blocked refund has no claim. One refund settled across a plan leg and a card leg, one has an external leg the source cannot reconcile, and one has a failed card leg beside a completed plan leg. Four claims in different states.',
  },
  {
    personaId: 'cus_sa_omar',
    label: 'Omar — Dammam',
    brief:
      'The account exists but the platform has not raised assurance to the level a payment trace requires.',
  },
] as const;

const customers = [
  {
    customer_id: 'cus_sa_amal',
    display_name: 'Amal',
    market: 'SA',
    currency: SAR,
    language: 'en',
    verification_state: 'verified',
  },
  {
    customer_id: 'cus_sa_faisal',
    display_name: 'Faisal',
    market: 'SA',
    currency: SAR,
    language: 'en',
    verification_state: 'verified',
  },
  {
    customer_id: 'cus_ae_rana',
    display_name: 'Rana',
    market: 'AE',
    currency: AED,
    language: 'en',
    verification_state: 'verified',
  },
  {
    customer_id: 'cus_sa_omar',
    display_name: 'Omar',
    market: 'SA',
    currency: SAR,
    language: 'en',
    verification_state: 'step_up_required',
  },
];

const orders = [
  // Amal — the refund cases.
  {
    order_ref: 'ORD-1001',
    customer_id: 'cus_sa_amal',
    merchant_display_name: 'Noon',
    merchant_id: 'mer_noon',
    total: sar(450),
    lifecycle: 'active',
    created_at: ago(40),
    customer_safe_status: 'Refund requested',
    claim_eligibility: 'ineligible',
    claim_eligibility_reason: 'A refund is already in progress with the merchant.',
  },
  {
    order_ref: 'ORD-1002',
    customer_id: 'cus_sa_amal',
    merchant_display_name: 'Jarir',
    merchant_id: 'mer_jarir',
    total: sar(200),
    lifecycle: 'active',
    created_at: ago(75),
    customer_safe_status: 'Refund requested',
    claim_eligibility: 'eligible',
    claim_eligibility_reason: 'The merchant refund is past its approved window.',
  },
  {
    order_ref: 'ORD-1003',
    customer_id: 'cus_sa_amal',
    merchant_display_name: 'Extra',
    merchant_id: 'mer_extra',
    total: sar(300),
    lifecycle: 'refunded',
    created_at: ago(60),
    customer_safe_status: 'Refunded',
    claim_eligibility: 'ineligible',
    claim_eligibility_reason: 'The order is fully refunded.',
  },
  {
    order_ref: 'ORD-1004',
    customer_id: 'cus_sa_amal',
    merchant_display_name: 'Namshi',
    merchant_id: 'mer_namshi',
    total: sar(500),
    lifecycle: 'active',
    created_at: ago(20),
    customer_safe_status: 'Paying in instalments',
    claim_eligibility: 'eligible',
    claim_eligibility_reason: 'No refund has been requested.',
  },
  // Faisal — the decline cases.
  {
    order_ref: 'ORD-1101',
    customer_id: 'cus_sa_faisal',
    merchant_display_name: 'IKEA',
    merchant_id: 'mer_ikea',
    total: sar(1200),
    lifecycle: 'declined',
    created_at: ago(3),
    customer_safe_status: 'Not approved',
    decline_code: 'credit_decision',
    decline_recurrence: 1,
    decline_last_at: ago(3),
    claim_eligibility: 'ineligible',
    claim_eligibility_reason: 'The order was never placed.',
  },
  {
    order_ref: 'ORD-1102',
    customer_id: 'cus_sa_faisal',
    merchant_display_name: 'Panda',
    merchant_id: 'mer_panda',
    total: sar(90),
    lifecycle: 'declined',
    created_at: hoursAgo(2),
    customer_safe_status: 'Not completed',
    decline_code: 'issuer_timeout',
    decline_recurrence: 1,
    decline_last_at: hoursAgo(2),
    claim_eligibility: 'ineligible',
    claim_eligibility_reason: 'The order was never placed.',
  },
  {
    order_ref: 'ORD-1103',
    customer_id: 'cus_sa_faisal',
    merchant_display_name: 'Panda',
    merchant_id: 'mer_panda',
    total: sar(90),
    lifecycle: 'declined',
    created_at: hoursAgo(30),
    customer_safe_status: 'Not completed',
    decline_code: 'issuer_timeout',
    decline_recurrence: 3,
    decline_last_at: hoursAgo(30),
    claim_eligibility: 'ineligible',
    claim_eligibility_reason: 'The order was never placed.',
  },
  {
    order_ref: 'ORD-1104',
    customer_id: 'cus_sa_faisal',
    merchant_display_name: 'Centrepoint',
    merchant_id: 'mer_centrepoint',
    total: sar(410),
    lifecycle: 'declined',
    created_at: ago(1),
    customer_safe_status: 'Not completed',
    decline_code: 'zz_unmapped_code',
    decline_recurrence: 1,
    decline_last_at: ago(1),
    claim_eligibility: 'ineligible',
    claim_eligibility_reason: 'The order was never placed.',
  },
  {
    order_ref: 'ORD-1105',
    customer_id: 'cus_sa_faisal',
    merchant_display_name: 'Jarir',
    merchant_id: 'mer_jarir',
    total: sar(249.5),
    lifecycle: 'active',
    created_at: ago(2),
    customer_safe_status: 'Awaiting first payment',
    claim_eligibility: 'unknown',
    claim_eligibility_reason: 'The payment for this order has not been reconciled.',
  },
  // Rana — merchant blocks, split settlement, failed legs.
  {
    order_ref: 'ORD-1201',
    customer_id: 'cus_ae_rana',
    merchant_display_name: 'Amazon.ae',
    merchant_id: 'mer_amazon_ae',
    total: aed(320),
    lifecycle: 'active',
    created_at: ago(45),
    customer_safe_status: 'Refund disputed',
    claim_eligibility: 'ineligible',
    claim_eligibility_reason: 'A dispute claim is already open for this order.',
  },
  {
    order_ref: 'ORD-1202',
    customer_id: 'cus_ae_rana',
    merchant_display_name: 'Carrefour',
    merchant_id: 'mer_carrefour',
    total: aed(300),
    lifecycle: 'active',
    created_at: ago(50),
    customer_safe_status: 'Refund declined by merchant',
    claim_eligibility: 'eligible',
    claim_eligibility_reason: 'The merchant has declined the refund and no claim exists.',
  },
  {
    order_ref: 'ORD-1203',
    customer_id: 'cus_ae_rana',
    merchant_display_name: 'Sharaf DG',
    merchant_id: 'mer_sharaf',
    total: aed(300),
    lifecycle: 'refunded',
    created_at: ago(30),
    customer_safe_status: 'Refunded',
    claim_eligibility: 'ineligible',
    claim_eligibility_reason: 'The order is fully refunded.',
  },
  {
    order_ref: 'ORD-1204',
    customer_id: 'cus_ae_rana',
    merchant_display_name: 'Noon',
    merchant_id: 'mer_noon',
    total: aed(200),
    lifecycle: 'refunded',
    created_at: ago(28),
    customer_safe_status: 'Refunded',
    claim_eligibility: 'unknown',
    claim_eligibility_reason: 'One settlement leg has not been reconciled.',
  },
  {
    order_ref: 'ORD-1205',
    customer_id: 'cus_ae_rana',
    merchant_display_name: 'Namshi',
    merchant_id: 'mer_namshi',
    total: aed(300),
    lifecycle: 'active',
    created_at: ago(25),
    customer_safe_status: 'Refund partly failed',
    claim_eligibility: 'eligible',
    claim_eligibility_reason: 'A settlement leg failed.',
  },
  // The order whose claims section cannot be read (OI-F2).
  {
    order_ref: 'ORD-1206',
    customer_id: 'cus_ae_rana',
    merchant_display_name: 'Ounass',
    merchant_id: 'mer_ounass',
    total: aed(1500),
    lifecycle: 'active',
    created_at: ago(15),
    customer_safe_status: 'Paying in instalments',
    claims_source_key: 'claims_partial_outage',
    claim_eligibility: 'unknown',
    claim_eligibility_reason: 'The dispute service did not answer.',
  },
];

const instalments = [
  {
    ref: 'INS-1001-1',
    order: 'ORD-1001',
    cust: 'cus_sa_amal',
    amt: sar(150),
    state: 'paid',
    due: ago(40),
    pay: 'PAY-2001',
  },
  {
    ref: 'INS-1001-2',
    order: 'ORD-1001',
    cust: 'cus_sa_amal',
    amt: sar(150),
    state: 'scheduled',
    due: ahead(5),
    pay: null,
  },
  {
    ref: 'INS-1001-3',
    order: 'ORD-1001',
    cust: 'cus_sa_amal',
    amt: sar(150),
    state: 'scheduled',
    due: ahead(35),
    pay: null,
  },
  {
    ref: 'INS-1004-1',
    order: 'ORD-1004',
    cust: 'cus_sa_amal',
    amt: sar(125),
    state: 'paid',
    due: ago(20),
    pay: 'PAY-2002',
  },
  {
    ref: 'INS-1004-2',
    order: 'ORD-1004',
    cust: 'cus_sa_amal',
    amt: sar(125),
    state: 'late',
    due: ago(2),
    pay: null,
  },
  {
    ref: 'INS-1004-3',
    order: 'ORD-1004',
    cust: 'cus_sa_amal',
    amt: sar(125),
    state: 'scheduled',
    due: ahead(28),
    pay: null,
  },
  {
    ref: 'INS-1004-4',
    order: 'ORD-1004',
    cust: 'cus_sa_amal',
    amt: sar(125),
    state: 'scheduled',
    due: ahead(58),
    pay: null,
  },
  {
    ref: 'INS-1003-1',
    order: 'ORD-1003',
    cust: 'cus_sa_amal',
    amt: sar(300),
    state: 'cancelled',
    due: ago(30),
    pay: null,
  },
  {
    ref: 'INS-1002-1',
    order: 'ORD-1002',
    cust: 'cus_sa_amal',
    amt: sar(200),
    state: 'paid',
    due: ago(75),
    pay: 'PAY-2003',
  },
  {
    ref: 'INS-1105-1',
    order: 'ORD-1105',
    cust: 'cus_sa_faisal',
    amt: sar(249.5),
    state: 'scheduled',
    due: ahead(3),
    pay: null,
  },
  {
    ref: 'INS-1201-1',
    order: 'ORD-1201',
    cust: 'cus_ae_rana',
    amt: aed(160),
    state: 'paid',
    due: ago(45),
    pay: 'PAY-2202',
  },
  {
    ref: 'INS-1201-2',
    order: 'ORD-1201',
    cust: 'cus_ae_rana',
    amt: aed(160),
    state: 'scheduled',
    due: ahead(15),
    pay: null,
  },
  {
    ref: 'INS-1206-1',
    order: 'ORD-1206',
    cust: 'cus_ae_rana',
    amt: aed(750),
    state: 'paid',
    due: ago(15),
    pay: 'PAY-2203',
  },
  {
    ref: 'INS-1206-2',
    order: 'ORD-1206',
    cust: 'cus_ae_rana',
    amt: aed(750),
    state: 'scheduled',
    due: ahead(15),
    pay: null,
  },
].map((i) => ({
  instalment_ref: i.ref,
  customer_id: i.cust,
  order_ref: i.order,
  due_date: i.due,
  amount: i.amt,
  state: i.state,
  payment_ref: i.pay,
}));

const payments = [
  {
    payment_ref: 'PAY-2001',
    customer_id: 'cus_sa_amal',
    amount: 150,
    currency: SAR,
    occurred_at: ago(40),
    descriptor: 'TAMARA*NOON',
    state: 'captured',
    last_four: '4242',
    payment_method_summary: 'Visa ···· 4242',
    order_ref: 'ORD-1001',
    applied_amount: 150,
    obligation_ref: 'OBL-1001',
    remaining_amount: 300,
    bank_debit: 'confirmed',
    bank_reversal: 'unknown',
    bank_evidence_source: 'issuer_feed',
    source_keys: [],
  },
  {
    payment_ref: 'PAY-2002',
    customer_id: 'cus_sa_amal',
    amount: 125,
    currency: SAR,
    occurred_at: ago(20),
    descriptor: 'TAMARA*NAMSHI',
    state: 'captured',
    last_four: '4242',
    payment_method_summary: 'Visa ···· 4242',
    order_ref: 'ORD-1004',
    applied_amount: 125,
    obligation_ref: 'OBL-1004',
    remaining_amount: 375,
    bank_debit: 'confirmed',
    bank_reversal: 'unknown',
    bank_evidence_source: 'issuer_feed',
    source_keys: [],
  },
  {
    payment_ref: 'PAY-2003',
    customer_id: 'cus_sa_amal',
    amount: 200,
    currency: SAR,
    occurred_at: ago(75),
    descriptor: 'TAMARA*JARIR',
    state: 'captured',
    last_four: '1881',
    payment_method_summary: 'Mada ···· 1881',
    order_ref: 'ORD-1002',
    applied_amount: 200,
    obligation_ref: 'OBL-1002',
    remaining_amount: 0,
    bank_debit: 'confirmed',
    bank_reversal: 'unknown',
    bank_evidence_source: 'issuer_feed',
    source_keys: [],
  },
  // Faisal — PI-09: captured, never applied, market policy known, not wallet-eligible.
  {
    payment_ref: 'PAY-2101',
    customer_id: 'cus_sa_faisal',
    amount: 249.5,
    currency: SAR,
    occurred_at: ago(2),
    descriptor: 'TAMARA*JARIR',
    state: 'captured',
    last_four: '7711',
    payment_method_summary: 'Visa ···· 7711',
    order_ref: 'ORD-1105',
    applied_amount: null,
    obligation_ref: null,
    remaining_amount: null,
    bank_debit: 'confirmed',
    bank_reversal: 'unknown',
    bank_evidence_source: 'issuer_feed',
    wallet_refund_eligible: false,
    source_keys: [],
  },
  // PI-01 — reflected.
  {
    payment_ref: 'PAY-2102',
    customer_id: 'cus_sa_faisal',
    amount: 100,
    currency: SAR,
    occurred_at: ago(9),
    descriptor: 'TAMARA*IKEA',
    state: 'captured',
    last_four: '7711',
    payment_method_summary: 'Visa ···· 7711',
    order_ref: 'ORD-1105',
    applied_amount: 100,
    obligation_ref: 'OBL-1105',
    remaining_amount: 149.5,
    bank_debit: 'confirmed',
    bank_reversal: 'unknown',
    bank_evidence_source: 'issuer_feed',
    source_keys: [],
  },
  // PI-02 — an authorisation hold with no capture.
  {
    payment_ref: 'PAY-2103',
    customer_id: 'cus_sa_faisal',
    amount: 75,
    currency: SAR,
    occurred_at: hoursAgo(20),
    descriptor: 'TAMARA*PANDA',
    state: 'authorized',
    last_four: '7711',
    payment_method_summary: 'Visa ···· 7711',
    order_ref: null,
    applied_amount: null,
    bank_debit: 'unknown',
    bank_reversal: 'unknown',
    bank_evidence_source: null,
    source_keys: [],
  },
  // PI-05 — a duplicate whose correction is already in flight.
  {
    payment_ref: 'PAY-2104',
    customer_id: 'cus_sa_faisal',
    amount: 120,
    currency: SAR,
    occurred_at: ago(6),
    descriptor: 'TAMARA*CENTREPOINT',
    state: 'captured',
    last_four: '7711',
    payment_method_summary: 'Visa ···· 7711',
    order_ref: 'ORD-1105',
    applied_amount: 120,
    obligation_ref: 'OBL-1105',
    remaining_amount: 29.5,
    bank_debit: 'confirmed',
    bank_reversal: 'unknown',
    bank_evidence_source: 'issuer_feed',
    source_keys: [],
  },
  {
    payment_ref: 'PAY-2105',
    customer_id: 'cus_sa_faisal',
    amount: 120,
    currency: SAR,
    occurred_at: ago(6),
    descriptor: 'TAMARA*CENTREPOINT',
    state: 'captured',
    last_four: '7711',
    payment_method_summary: 'Visa ···· 7711',
    order_ref: 'ORD-1105',
    applied_amount: null,
    duplicate_of: 'PAY-2104',
    bank_debit: 'confirmed',
    bank_reversal: 'unknown',
    bank_evidence_source: 'issuer_feed',
    remediation: {
      state: 'pending',
      amount: sar(120),
      expected_by: ahead(2),
      reference: 'RFD-3101',
    },
    source_keys: [],
  },
  // PI-06 — a duplicate with no correction anywhere.
  {
    payment_ref: 'PAY-2106',
    customer_id: 'cus_sa_faisal',
    amount: 80,
    currency: SAR,
    occurred_at: ago(4),
    descriptor: 'TAMARA*PANDA',
    state: 'captured',
    last_four: '7711',
    payment_method_summary: 'Visa ···· 7711',
    order_ref: 'ORD-1105',
    applied_amount: null,
    duplicate_of: 'PAY-2107',
    bank_debit: 'confirmed',
    bank_reversal: 'unknown',
    bank_evidence_source: 'issuer_feed',
    remediation: null,
    source_keys: [],
  },
  {
    payment_ref: 'PAY-2107',
    customer_id: 'cus_sa_faisal',
    amount: 80,
    currency: SAR,
    occurred_at: ago(4),
    descriptor: 'TAMARA*PANDA',
    state: 'captured',
    last_four: '7711',
    payment_method_summary: 'Visa ···· 7711',
    order_ref: 'ORD-1105',
    applied_amount: 80,
    obligation_ref: 'OBL-1105',
    remaining_amount: 0,
    bank_debit: 'confirmed',
    bank_reversal: 'unknown',
    bank_evidence_source: 'issuer_feed',
    source_keys: [],
  },
  // PI-11 — declined, and the bank still shows a debit.
  {
    payment_ref: 'PAY-2108',
    customer_id: 'cus_sa_faisal',
    amount: 60,
    currency: SAR,
    occurred_at: hoursAgo(30),
    descriptor: 'TAMARA*PANDA',
    state: 'declined',
    last_four: '7711',
    payment_method_summary: 'Visa ···· 7711',
    order_ref: null,
    applied_amount: null,
    bank_debit: 'confirmed',
    bank_reversal: 'pending',
    bank_evidence_source: 'customer_statement',
    source_keys: [],
  },
  // PI-03 — an authoritative reversal.
  {
    payment_ref: 'PAY-2109',
    customer_id: 'cus_sa_faisal',
    amount: 90,
    currency: SAR,
    occurred_at: ago(8),
    descriptor: 'TAMARA*IKEA',
    state: 'reversed',
    last_four: '7711',
    payment_method_summary: 'Visa ···· 7711',
    order_ref: null,
    applied_amount: null,
    bank_debit: 'confirmed',
    bank_reversal: 'confirmed',
    bank_evidence_source: 'acquirer_feed',
    source_keys: [],
  },
  // PI-07 — the ledger source for this payment is lagging.
  {
    payment_ref: 'PAY-2110',
    customer_id: 'cus_sa_faisal',
    amount: 45,
    currency: SAR,
    occurred_at: hoursAgo(3),
    descriptor: 'TAMARA*PANDA',
    state: 'captured',
    last_four: '7711',
    payment_method_summary: 'Visa ···· 7711',
    order_ref: 'ORD-1105',
    applied_amount: null,
    bank_debit: 'confirmed',
    bank_reversal: 'unknown',
    bank_evidence_source: 'issuer_feed',
    source_keys: ['ledger_lag'],
  },
  // The bank turned these two away, so each declined checkout has a declined
  // ATTEMPT behind it. ORD-1101 deliberately has none: a credit decision is
  // ours and is made before a card is ever presented, so a payment row there
  // would describe an attempt nobody made.
  {
    payment_ref: 'PAY-2112',
    customer_id: 'cus_sa_faisal',
    amount: 22.5,
    currency: SAR,
    occurred_at: hoursAgo(2),
    descriptor: 'TAMARA*PANDA',
    state: 'declined',
    last_four: '7711',
    payment_method_summary: 'Visa ···· 7711',
    order_ref: 'ORD-1102',
    applied_amount: null,
    bank_debit: 'unknown',
    bank_reversal: 'unknown',
    bank_evidence_source: null,
    source_keys: [],
  },
  {
    payment_ref: 'PAY-2113',
    customer_id: 'cus_sa_faisal',
    amount: 22.5,
    currency: SAR,
    occurred_at: hoursAgo(30),
    descriptor: 'TAMARA*PANDA',
    state: 'declined',
    last_four: '7711',
    payment_method_summary: 'Visa ···· 7711',
    order_ref: 'ORD-1103',
    applied_amount: null,
    bank_debit: 'unknown',
    bank_reversal: 'unknown',
    bank_evidence_source: null,
    source_keys: [],
  },
  // PI-08 — KSA wallet-refund eligibility, authoritatively established.
  {
    payment_ref: 'PAY-2111',
    customer_id: 'cus_sa_faisal',
    amount: 310,
    currency: SAR,
    occurred_at: ago(5),
    descriptor: 'TAMARA*IKEA',
    state: 'captured',
    last_four: '7711',
    payment_method_summary: 'Visa ···· 7711',
    order_ref: 'ORD-1105',
    applied_amount: null,
    bank_debit: 'confirmed',
    bank_reversal: 'unknown',
    bank_evidence_source: 'issuer_feed',
    wallet_refund_eligible: true,
    wallet_refund_eligibility_ref: 'ELIG-9001',
    source_keys: [],
  },
  // Rana.
  {
    payment_ref: 'PAY-2201',
    customer_id: 'cus_ae_rana',
    amount: 200,
    currency: AED,
    occurred_at: ago(28),
    descriptor: 'TAMARA*NOON',
    state: 'refunded',
    last_four: '9002',
    payment_method_summary: 'Mastercard ···· 9002',
    order_ref: 'ORD-1204',
    applied_amount: 200,
    obligation_ref: 'OBL-1204',
    remaining_amount: 0,
    bank_debit: 'confirmed',
    bank_reversal: 'unknown',
    bank_evidence_source: 'issuer_feed',
    source_keys: [],
  },
  {
    payment_ref: 'PAY-2202',
    customer_id: 'cus_ae_rana',
    amount: 160,
    currency: AED,
    occurred_at: ago(45),
    descriptor: 'TAMARA*AMAZONAE',
    state: 'captured',
    last_four: '9002',
    payment_method_summary: 'Mastercard ···· 9002',
    order_ref: 'ORD-1201',
    applied_amount: 160,
    obligation_ref: 'OBL-1201',
    remaining_amount: 160,
    bank_debit: 'confirmed',
    bank_reversal: 'unknown',
    bank_evidence_source: 'issuer_feed',
    source_keys: [],
  },
  {
    payment_ref: 'PAY-2204',
    customer_id: 'cus_ae_rana',
    amount: 300,
    currency: AED,
    occurred_at: ago(25),
    descriptor: 'TAMARA*NAMSHI',
    state: 'captured',
    last_four: '9002',
    payment_method_summary: 'Mastercard ···· 9002',
    order_ref: 'ORD-1205',
    applied_amount: 300,
    obligation_ref: 'OBL-1205',
    remaining_amount: 0,
    bank_debit: 'confirmed',
    bank_reversal: 'unknown',
    bank_evidence_source: 'issuer_feed',
    source_keys: [],
  },
  {
    payment_ref: 'PAY-2203',
    customer_id: 'cus_ae_rana',
    amount: 750,
    currency: AED,
    occurred_at: ago(15),
    descriptor: 'TAMARA*OUNASS',
    state: 'captured',
    last_four: '9002',
    payment_method_summary: 'Mastercard ···· 9002',
    order_ref: 'ORD-1206',
    applied_amount: 750,
    obligation_ref: 'OBL-1206',
    remaining_amount: 750,
    bank_debit: 'confirmed',
    bank_reversal: 'unknown',
    bank_evidence_source: 'issuer_feed',
    source_keys: [],
  },
];

const refunds = [
  // OI-R2 — pending with the merchant, inside the approved window.
  {
    refund_ref: 'RFD-3001',
    customer_id: 'cus_sa_amal',
    order_ref: 'ORD-1001',
    payment_ref: 'PAY-2001',
    state: 'pending_merchant',
    owner: 'merchant',
    total: sar(450),
    requested_at: ago(4),
    allocations: [],
    resulting_balance: sar(300),
  },
  // OI-R3 — the same shape, well past the deadline, with investigation required.
  {
    refund_ref: 'RFD-3002',
    customer_id: 'cus_sa_amal',
    order_ref: 'ORD-1002',
    payment_ref: 'PAY-2003',
    state: 'pending_merchant',
    owner: 'merchant',
    total: sar(200),
    requested_at: ago(62),
    allocations: [],
    resulting_balance: sar(0),
    investigation_required_when_overdue: true,
  },
  // OI-R5 — settled entirely against the plan, so no external leg to trace.
  {
    refund_ref: 'RFD-3003',
    customer_id: 'cus_sa_amal',
    order_ref: 'ORD-1003',
    payment_ref: null,
    state: 'processed',
    owner: 'tamara',
    total: sar(300),
    requested_at: ago(31),
    fees: [{ label: 'Late fee reversed', amount: sar(0) }],
    allocations: [
      {
        destination: 'plan',
        amount: sar(300),
        state: 'processed',
        processed_at: ago(30),
        trace_reference: null,
        reconciled: true,
      },
    ],
    resulting_balance: sar(0),
  },
  // OI-R9 — merchant block with a dispute claim already open.
  {
    refund_ref: 'RFD-3201',
    customer_id: 'cus_ae_rana',
    order_ref: 'ORD-1201',
    payment_ref: 'PAY-2202',
    state: 'merchant_blocked',
    owner: 'merchant',
    total: aed(320),
    requested_at: ago(20),
    allocations: [],
    resulting_balance: aed(160),
  },
  // OI-R10 — merchant block with complete coverage and no claim anywhere.
  {
    refund_ref: 'RFD-3202',
    customer_id: 'cus_ae_rana',
    order_ref: 'ORD-1202',
    payment_ref: null,
    state: 'merchant_blocked',
    owner: 'merchant',
    total: aed(300),
    requested_at: ago(18),
    allocations: [],
    resulting_balance: aed(300),
  },
  // OI-R6 — a plan leg and a card leg, both consistent.
  {
    refund_ref: 'RFD-3203',
    customer_id: 'cus_ae_rana',
    order_ref: 'ORD-1203',
    payment_ref: null,
    state: 'processed',
    owner: 'tamara',
    total: aed(300),
    requested_at: ago(12),
    allocations: [
      {
        destination: 'plan',
        amount: aed(100),
        state: 'processed',
        processed_at: ago(11),
        trace_reference: null,
        reconciled: true,
      },
      {
        destination: 'card',
        amount: aed(200),
        state: 'processed',
        processed_at: ago(10),
        trace_reference: 'ARN-77120033',
        reconciled: true,
      },
    ],
    resulting_balance: aed(0),
  },
  // OI-R8 — an external leg the source cannot reconcile.
  {
    refund_ref: 'RFD-3204',
    customer_id: 'cus_ae_rana',
    order_ref: 'ORD-1204',
    payment_ref: 'PAY-2201',
    state: 'processed',
    owner: 'tamara',
    total: aed(200),
    requested_at: ago(9),
    allocations: [
      {
        destination: 'plan',
        amount: aed(50),
        state: 'processed',
        processed_at: ago(8),
        trace_reference: null,
        reconciled: true,
      },
      {
        destination: 'card',
        amount: aed(150),
        state: 'processed',
        processed_at: ago(8),
        trace_reference: null,
        reconciled: false,
      },
    ],
    resulting_balance: aed(0),
  },
  // OI-R7 — a failed card leg beside a completed plan leg.
  {
    refund_ref: 'RFD-3205',
    customer_id: 'cus_ae_rana',
    order_ref: 'ORD-1205',
    payment_ref: 'PAY-2204',
    state: 'failed',
    owner: 'tamara',
    total: aed(300),
    requested_at: ago(7),
    allocations: [
      {
        destination: 'plan',
        amount: aed(100),
        state: 'processed',
        processed_at: ago(6),
        trace_reference: null,
        reconciled: true,
      },
      {
        destination: 'card',
        amount: aed(200),
        state: 'failed',
        processed_at: null,
        trace_reference: 'ARN-88210044',
        reconciled: true,
      },
    ],
    resulting_balance: aed(200),
  },
];

const claims = [
  {
    claim_ref: 'CLM-4201',
    customer_id: 'cus_ae_rana',
    order_ref: 'ORD-1201',
    state: 'under_review',
    summary: 'Merchant declined the refund; goods were returned in store.',
    owner: 'merchant',
    required_party: 'merchant',
    customer_action: null,
    evidence_requirements: [],
    human_action_in_progress: true,
    expected_update_at: ahead(6),
    outcome: null,
  },
  {
    claim_ref: 'CLM-4202',
    customer_id: 'cus_ae_rana',
    order_ref: 'ORD-1205',
    state: 'waiting_customer',
    summary: 'Proof of return is needed before the dispute can proceed.',
    owner: 'tamara',
    required_party: 'customer',
    customer_action: 'Upload the courier receipt showing the parcel was returned.',
    evidence_requirements: ['courier_receipt', 'return_reference'],
    human_action_in_progress: false,
    expected_update_at: ahead(3),
    outcome: null,
  },
  {
    claim_ref: 'CLM-4203',
    customer_id: 'cus_ae_rana',
    order_ref: 'ORD-1203',
    state: 'resolved',
    summary: 'Dispute upheld; the refund was settled across the plan and the card.',
    owner: 'scheme',
    required_party: null,
    customer_action: null,
    evidence_requirements: [],
    human_action_in_progress: false,
    expected_update_at: null,
    outcome: 'Refund settled in full on 300 AED.',
  },
  {
    claim_ref: 'CLM-4204',
    customer_id: 'cus_ae_rana',
    order_ref: 'ORD-1204',
    state: 'under_review',
    summary: 'The card leg of the refund cannot be traced to a settlement record.',
    owner: 'tamara',
    required_party: 'tamara',
    customer_action: null,
    evidence_requirements: [],
    human_action_in_progress: true,
    expected_update_at: ago(5),
    outcome: null,
    deadline_policy_key: 'claim_update_deadline',
  },
];

const knowledgeArticles = [
  {
    article_id: 'KB-001',
    topic: 'refunds',
    market: 'SA',
    language: 'en',
    title: 'How long a refund takes',
    body: 'A merchant has 14 days to return the money once they accept the return. Once it reaches us, the payment plan is adjusted the same day and any amount already paid is returned to the original card within 5 working days.',
    conditions: [
      'The 14 days start when the merchant accepts the return, not when it is posted.',
      'A refund is applied to the remaining instalments before anything is returned to the card.',
    ],
    version: '3',
    effective_from: ago(200),
    effective_to: null,
    links: [],
  },
  {
    article_id: 'KB-002',
    topic: 'refunds',
    market: 'SA',
    language: 'ar',
    title: 'كم تستغرق عملية الاسترداد',
    body: 'أمام المتجر ١٤ يوماً لإعادة المبلغ بعد قبول الإرجاع. وعند وصوله إلينا تُعدَّل خطة السداد في اليوم نفسه، ويُعاد أي مبلغ مدفوع إلى البطاقة خلال ٥ أيام عمل.',
    conditions: ['تبدأ مدة الأربعة عشر يوماً من قبول المتجر للإرجاع لا من تاريخ الإرسال.'],
    version: '3',
    effective_from: ago(200),
    effective_to: null,
    links: [],
  },
  // Withdrawn — must never be selected, which is KS-03's boundary test.
  {
    article_id: 'KB-010',
    topic: 'refunds',
    market: 'SA',
    language: 'en',
    title: 'How long a refund takes (withdrawn)',
    body: 'A merchant has 30 days to return the money.',
    version: '2',
    effective_from: ago(400),
    effective_to: ago(200),
    links: [],
  },
  {
    article_id: 'KB-007',
    topic: 'refunds',
    market: 'AE',
    language: 'en',
    title: 'How long a refund takes',
    body: 'A merchant has 14 days to return the money once they accept the return. The payment plan is adjusted the same day it reaches us.',
    version: '2',
    effective_from: ago(150),
    effective_to: null,
    links: [],
  },
  // KS-04 — approved guidance whose app path is not approved in this market.
  {
    article_id: 'KB-003',
    topic: 'purchase_limits',
    market: 'SA',
    language: 'en',
    title: 'Why a spending limit changes',
    body: 'A limit is set per order from repayment history, how many plans are open, and the merchant. It moves on its own as instalments are paid and is not something support can raise by hand.',
    conditions: ['A limit is decided per order rather than held on the account.'],
    version: '4',
    effective_from: ago(120),
    effective_to: null,
    links: [],
    missing_link_label: 'Check your limit in the app',
    missing_link_fallback:
      'There is no approved deep link for this market yet. Point the customer to the app home screen, where the available limit is shown before checkout.',
  },
  // KS-02 — two products under one topic, so the question needs a discriminator.
  {
    article_id: 'KB-008',
    topic: 'purchase_limits',
    market: 'SA',
    language: 'en',
    title: 'Minimum and maximum for Pay in 4',
    body: 'Pay in 4 runs from 50 SAR to 5,000 SAR per order.',
    version: '2',
    effective_from: ago(120),
    effective_to: null,
    links: [],
    product: 'pay_in_4',
  },
  {
    article_id: 'KB-009',
    topic: 'purchase_limits',
    market: 'SA',
    language: 'en',
    title: 'Minimum and maximum for Pay in 30',
    body: 'Pay in 30 runs from 100 SAR to 2,500 SAR per order.',
    version: '2',
    effective_from: ago(120),
    effective_to: null,
    links: [],
    product: 'pay_in_30',
  },
  // KS-03 — complete, including the app path it was asked for.
  {
    article_id: 'KB-004',
    topic: 'prequalification',
    market: 'SA',
    language: 'en',
    title: 'Check what you can spend before you shop',
    body: 'The app shows the amount available for the next order before checkout, under Pay with Tamara.',
    version: '5',
    effective_from: ago(90),
    effective_to: null,
    links: [{ label: 'Open pre-qualification', url: 'https://app.tamara.co/prequalify' }],
  },
  {
    article_id: 'KB-005',
    topic: 'declined_orders',
    market: 'SA',
    language: 'en',
    title: 'When a checkout is not approved',
    body: 'Each order is assessed on its own. A checkout can be declined while another the same day is approved, and support cannot override the outcome.',
    conditions: ['The decision is per order and is not a judgement about the account.'],
    version: '6',
    effective_from: ago(75),
    effective_to: null,
    links: [],
  },
  {
    article_id: 'KB-006',
    topic: 'payment_reversals',
    market: 'SA',
    language: 'en',
    title: 'A payment that was taken and then returned',
    body: 'When an attempt fails after the bank has already held the money, the hold is released by the bank. It usually clears within 5 working days and no action is needed.',
    version: '3',
    effective_from: ago(60),
    effective_to: null,
    links: [],
  },
];

const policies = [
  {
    policy_key: 'refund_deadlines',
    market: '*',
    value: { merchant_days: 14, tamara_days: 5 },
    version: '2026.06',
  },
  {
    policy_key: 'claim_update_deadline',
    market: '*',
    value: { escalation_reason: 'refund_failure' },
    version: '2026.06',
  },
  {
    policy_key: 'knowledge_fallback',
    market: 'SA',
    value: {
      human_support: true,
      description: 'Support can look at the account and answer questions policy does not cover.',
    },
    version: '2026.06',
  },
  {
    policy_key: 'knowledge_fallback',
    market: 'AE',
    value: {
      human_support: true,
      description: 'Support can look at the account and answer questions policy does not cover.',
    },
    version: '2026.06',
  },
  {
    policy_key: 'search_limits',
    market: '*',
    value: {
      page_size: 2,
      max_window_days: 90,
      cursor_ttl_ms: 900000,
      timezone_offset: '+03:00',
    },
    version: '2026.06',
  },
  {
    policy_key: 'order_picker',
    market: '*',
    value: { page_size: 2, default_scope_days: 400 },
    version: '2026.06',
  },
  {
    policy_key: 'authorization_hold',
    market: '*',
    value: { window_hours: 168 },
    version: '2026.06',
  },
  {
    policy_key: 'reconciliation',
    market: '*',
    value: { correction_window_hours: 24, escalation_reason: 'technical_investigation' },
    version: '2026.06',
  },
  // Declared for KSA only. An AE payment in the same shape reaches PI-09 instead,
  // which is the market boundary the specification leaves open and this pins.
  {
    policy_key: 'wallet_refund',
    market: 'SA',
    value: { enabled: true, escalation_reason: 'payment_not_reflected' },
    version: '2026.06',
  },
  {
    policy_key: 'handover_routing',
    market: '*',
    value: {
      queues: {
        technical_investigation: 'payments_engineering',
        refund_failure: 'refunds_recovery',
        merchant_blocked_refund: 'disputes',
        identity_verification_failed: 'secure_intake',
        unrecognized_charge_review: 'fraud_review',
        payment_not_reflected: 'refunds_recovery',
        fraud_risk_review: 'fraud_review',
        unknown_decline_code: 'payments_engineering',
        customer_requested_human: 'general_support',
        capability_unavailable: 'general_support',
        conflicting_data: 'payments_engineering',
      },
      confirmation_required: ['customer_requested_human', 'fraud_risk_review'],
      evidence_required: {
        unrecognized_charge_review: ['bank_statement'],
        payment_not_reflected: ['bank_statement'],
      },
      open_minute: 480,
      close_minute: 1320,
      timezone_offset_minutes: 180,
      out_of_hours_fallback: 'Leave the case for the team and they answer when the desk reopens.',
      out_of_hours_creates_case: true,
    },
    version: '2026.06',
  },
].map((p) => ({ ...p, policy_id: `${p.policy_key}:${p.market}`, effective_from: ago(120) }));

const declineCodes = [
  {
    code: 'credit_decision',
    classification: 'explainable',
    explanation:
      'The order was assessed on its own and was not approved. Each order is judged separately, and this says nothing about the account as a whole.',
    customer_actions: ['Try a smaller order.', 'Pay down an open plan and try again afterwards.'],
    retry_condition_key: null,
    retry_state: 'blocked',
    escalation_recurrence: null,
    escalation_reason: null,
    retry_after_hours: null,
  },
  {
    code: 'insufficient_funds',
    classification: 'explainable',
    explanation: 'The bank did not have the amount available when the first payment was taken.',
    customer_actions: ['Add funds and try again.', 'Use a different card.'],
    retry_condition_key: 'funds_available',
    retry_state: 'conditional',
    escalation_recurrence: null,
    escalation_reason: null,
    retry_after_hours: 0,
  },
  {
    code: 'card_expired',
    classification: 'explainable',
    explanation: 'The card on the order has passed its expiry date.',
    customer_actions: ['Add a current card and place the order again.'],
    retry_condition_key: 'card_replaced',
    retry_state: 'blocked',
    escalation_recurrence: null,
    escalation_reason: null,
    retry_after_hours: null,
  },
  {
    code: 'issuer_timeout',
    classification: 'technical',
    explanation: 'The bank did not answer in time, so the checkout could not be completed.',
    customer_actions: ['Try again in an hour.'],
    retry_condition_key: 'retry_after_elapsed',
    retry_state: 'conditional',
    escalation_recurrence: 3,
    escalation_reason: 'technical_investigation',
    retry_after_hours: 1,
  },
  {
    code: 'gateway_error',
    classification: 'technical',
    explanation: 'The payment service returned an error the checkout could not recover from.',
    customer_actions: ['Try again.'],
    retry_condition_key: 'retry_after_elapsed',
    retry_state: 'conditional',
    escalation_recurrence: 2,
    escalation_reason: 'technical_investigation',
    retry_after_hours: 0,
  },
];

const sourceHealth = [
  { source_key: 'knowledge', state: 'checked', applies_to: ['knowledge_search'] },
  { source_key: 'claims', state: 'checked', applies_to: ['claim_inspect', 'claims'] },
  {
    source_key: 'orders',
    state: 'checked',
    applies_to: ['orders_select', 'order_inspect', 'plan'],
  },
  { source_key: 'settlement', state: 'checked', applies_to: ['refund'] },
  { source_key: 'decline_map', state: 'checked', applies_to: ['decline_codes'] },
  { source_key: 'payments_index', state: 'checked', applies_to: ['payments_search'] },
  { source_key: 'ledger', state: 'checked', applies_to: ['payment_inspect', 'reconciliation'] },
  { source_key: 'issuer_feed', state: 'checked', applies_to: ['bank_state'] },
  {
    source_key: 'handover',
    state: 'checked',
    applies_to: ['handover_start'],
  },
  // Named by one payment rather than by a whole endpoint, so a single
  // reconciliation is pending while the rest of the world stays healthy.
  {
    source_key: 'ledger_lag',
    state: 'lagging',
    as_of: hoursAgo(4),
    recheck_at: new Date(CS_DESK_CLOCK_MS + 2 * hour).toISOString(),
    retryable: true,
    applies_to: ['ledger_lag'],
  },
  // The dispute service is degraded for exactly one order (OI-F2).
  {
    source_key: 'claims_partial_outage',
    state: 'failed',
    as_of: hoursAgo(1),
    retryable: true,
    applies_to: ['claims_partial_outage'],
  },
].map((s) => ({ as_of: hoursAgo(1), recheck_at: null, retryable: true, ...s }));

export const CS_DESK_BASELINE: Record<string, Array<Record<string, unknown>>> = {
  customers,
  orders,
  instalments,
  payments,
  refunds,
  claims,
  handover_cases: [],
  knowledge_articles: knowledgeArticles,
  policies,
  decline_codes: declineCodes,
  source_health: sourceHealth,
};
