/**
 * Contract: the `open` launcher is Claude Code's sandbox with every domain
 * allowed (Plan 315 D19). It admits every host the policy does not name but
 * this machine, on any port and under any spelling, and the profile the
 * adapter writes for the policy it runs on macOS grants no loopback at all. No
 * port is named anywhere: the machine's loopback is never a job's.
 *
 * The profile is the adapter's, generated by the version this lane pins, so a
 * change in its shape fails here rather than opening loopback.
 */
import { wrapCommandWithSandboxMacOS } from '@anthropic-ai/sandbox-runtime/dist/sandbox/macos-sandbox-utils.js';
import { describe, expect, it } from 'vitest';

import type { HostBinding } from '../bindings.js';
import { compileSandboxPolicy } from '../sandboxPolicy.js';

interface LauncherAnswers {
  admitUnlessThisMachine(options: {
    resolve: (host: string) => Promise<Array<{ address: string }>>;
    localAddresses: readonly string[];
  }): (request: { host: string; port: number }) => Promise<boolean>;
}

const launcher = (await import('../openSandboxLauncher.mjs')) as LauncherAnswers;

const LAN_ADDRESS = '192.168.50.7';
/** Ports a listener on this machine is known to hold: Redis, the MCP server, an admin tool. */
const MACHINE_PORTS = [6379, 3100, 8081, 41234];

describe('the `open` launcher’s answer for a host the policy does not name', () => {
  const answers: Record<string, string[]> = {
    localhost: ['127.0.0.1', '::1'],
    '127.0.0.1': ['127.0.0.1'],
    '127.0.0.2': ['127.0.0.2'],
    '127.1': ['127.0.0.1'],
    '0.0.0.0': ['0.0.0.0'],
    '::1': ['::1'],
    'rebound.example': ['::ffff:127.0.0.1'],
    'mixed.example': ['104.16.0.35', '127.0.0.1'],
    [LAN_ADDRESS]: [LAN_ADDRESS],
    'registry.npmjs.org': ['104.16.0.35'],
    'api.github.com': ['140.82.112.6', '2606:50c0:8000::154'],
  };
  const admit = launcher.admitUnlessThisMachine({
    resolve: (host) => {
      const found = answers[host];
      return found === undefined
        ? Promise.reject(new Error(`ENOTFOUND ${host}`))
        : Promise.resolve(found.map((address) => ({ address })));
    },
    localAddresses: [LAN_ADDRESS],
  });

  it('refuses this machine on every port, by every address it answers on and every name for it', async () => {
    for (const host of [
      'localhost',
      '127.0.0.1',
      '127.0.0.2',
      '127.1',
      '0.0.0.0',
      '[::1]',
      'rebound.example',
      'mixed.example',
      LAN_ADDRESS,
    ]) {
      for (const port of MACHINE_PORTS) {
        expect(await admit({ host, port }), `${host}:${String(port)}`).toBe(false);
      }
    }
  });

  it('refuses a host that does not resolve, since nothing then says where it goes', async () => {
    expect(await admit({ host: 'nowhere.invalid', port: 443 })).toBe(false);
  });

  it('admits every host off this machine, on any port', async () => {
    for (const host of ['registry.npmjs.org', 'api.github.com']) {
      for (const port of [...MACHINE_PORTS, 443]) {
        expect(await admit({ host, port }), `${host}:${String(port)}`).toBe(true);
      }
    }
  });
});

describe('the macOS profile an `open` job runs under', () => {
  /** The grant the adapter's profile opens every localhost port with. */
  const LOOPBACK_GRANT = '(allow network-outbound (remote ip "localhost:*"))';

  const binding: HostBinding = {
    id: 'hb',
    root: '/Users/probe/projects/demo',
    mode: 'readwrite',
    allowsExecution: true,
    singleFile: false,
  };

  function profileFor(allowLocalBinding: boolean | undefined): string {
    return wrapCommandWithSandboxMacOS({
      command: "'true'",
      needsNetworkRestriction: true,
      httpProxyPort: 40001,
      socksProxyPort: 40002,
      ...(allowLocalBinding === undefined ? {} : { allowLocalBinding }),
      readConfig: { denyOnly: ['/Users/probe'] },
      writeConfig: { allowOnly: ['/tmp/aflow-host'], denyWithinAllow: [] },
    });
  }

  it('grants no loopback, as the policy the launcher reads asks for none', () => {
    const policy = compileSandboxPolicy(binding, {
      home: '/Users/probe',
      scratchDir: '/tmp/aflow-host',
    });
    expect('allowLocalBinding' in policy.network).toBe(false);
    expect(profileFor(undefined)).not.toContain(LOOPBACK_GRANT);
    // The grant looked for is the adapter's own spelling of it.
    expect(profileFor(true)).toContain(LOOPBACK_GRANT);
  });
});
