/**
 * Contract: no job reaches the stack's own services (Plan 315 D19, F98). The
 * lane reads where they are from what it holds, the policy denies exactly those
 * ports under every loopback spelling, and the `open` launcher refuses them on
 * every address this machine answers on and, on macOS, in the adapter's own
 * profile — while every other loopback port stays admitted.
 *
 * The profile is the adapter's, generated by the version this lane pins, so a
 * change in its shape fails here rather than opening loopback whole.
 */
import { wrapCommandWithSandboxMacOS } from '@anthropic-ai/sandbox-runtime/dist/sandbox/macos-sandbox-utils.js';
import { SandboxRuntimeConfigSchema } from '@anthropic-ai/sandbox-runtime';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import type { HostBinding } from '../bindings.js';
import { compileSandboxPolicy } from '../sandboxPolicy.js';
import {
  STACK_API_PORT_DEFAULT,
  STACK_DATABASE_PORT_DEFAULT,
  STACK_WEB_PORT_DEFAULT,
  stackServiceDenials,
  stackServicesOf,
} from '../stackServices.js';

interface LauncherAnswers {
  stackServicePorts(deniedDomains: readonly string[]): Set<number>;
  admitUnlessStackService(
    ports: ReadonlySet<number>,
    options: {
      resolve: (host: string) => Promise<Array<{ address: string }>>;
      localAddresses: readonly string[];
    },
  ): (request: { host: string; port: number }) => Promise<boolean>;
  refuseStackServicesInProfile(
    wrapped: string,
    command: string,
    ports: ReadonlySet<number>,
  ): string;
  LOOPBACK_OUTBOUND_GRANT: string;
}

const launcher = (await import('../openSandboxLauncher.mjs')) as LauncherAnswers;

const REDIS_PORT = 6390;
const LAN_ADDRESS = '192.168.50.7';
const STACK_ENV = ['REDIS_URL', 'REDIS_HOST', 'REDIS_PORT', 'DATABASE_URL', 'AFLOW_API_URL'];

const saved = new Map<string, string | undefined>();
beforeEach(() => {
  for (const key of STACK_ENV) {
    saved.set(key, process.env[key]);
    delete process.env[key];
  }
});
afterEach(() => {
  for (const [key, value] of saved) {
    if (value === undefined) delete process.env[key];
    else process.env[key] = value;
  }
});

describe('where the stack’s services are', () => {
  it('reads Redis from the URL the lane was paired with, and the rest from the stack’s ports', () => {
    process.env['REDIS_URL'] = `redis://localhost:${String(REDIS_PORT)}`;
    expect(stackServicesOf().map(({ host, port }) => `${host}:${String(port)}`)).toEqual([
      `localhost:${String(REDIS_PORT)}`,
      `127.0.0.1:${String(STACK_DATABASE_PORT_DEFAULT)}`,
      `127.0.0.1:${String(STACK_API_PORT_DEFAULT)}`,
      `127.0.0.1:${String(STACK_WEB_PORT_DEFAULT)}`,
    ]);
  });

  it('takes the database and the API from the environment where it names them', () => {
    process.env['REDIS_URL'] = 'redis://:secret@10.0.0.5';
    process.env['DATABASE_URL'] = 'postgres://phoenix:phoenix@localhost:6543/phoenix';
    process.env['AFLOW_API_URL'] = 'https://aflow.example.com';
    expect(stackServicesOf().map(({ host, port }) => `${host}:${String(port)}`)).toEqual([
      '10.0.0.5:6379',
      'localhost:6543',
      'aflow.example.com:443',
      `127.0.0.1:${String(STACK_WEB_PORT_DEFAULT)}`,
    ]);
  });

  it('denies one on this machine under every loopback spelling, and one elsewhere by its host', () => {
    expect(
      stackServiceDenials([
        { host: 'localhost', port: REDIS_PORT },
        { host: '10.0.0.5', port: 3000 },
        { host: '[2001:db8::1]', port: 5432 },
      ]),
    ).toEqual([
      `localhost:${String(REDIS_PORT)}`,
      `127.0.0.1:${String(REDIS_PORT)}`,
      `[::1]:${String(REDIS_PORT)}`,
      '10.0.0.5:3000',
      '[2001:db8::1]:5432',
    ]);
  });
});

describe('the policy a job runs under', () => {
  const binding: HostBinding = {
    id: 'hb',
    root: '/Users/probe/projects/demo',
    mode: 'readwrite',
    singleFile: false,
  };

  it.each(['open', 'confined'] as const)(
    'denies the stack’s ports under `%s`, in a shape the adapter accepts',
    (posture) => {
      process.env['REDIS_URL'] = `redis://localhost:${String(REDIS_PORT)}`;
      const policy = compileSandboxPolicy(binding, {
        home: '/Users/probe',
        scratchDir: '/tmp/aflow-host',
        posture,
      });
      expect(policy.network.deniedDomains).toEqual(
        expect.arrayContaining([
          `localhost:${String(REDIS_PORT)}`,
          `127.0.0.1:${String(REDIS_PORT)}`,
          `[::1]:${String(REDIS_PORT)}`,
          `localhost:${String(STACK_API_PORT_DEFAULT)}`,
        ]),
      );
      expect(() => SandboxRuntimeConfigSchema.parse(policy)).not.toThrow();
    },
  );
});

describe('the `open` launcher’s answer for a host the policy does not name', () => {
  const ports = launcher.stackServicePorts([
    `localhost:${String(REDIS_PORT)}`,
    `127.0.0.1:${String(REDIS_PORT)}`,
    '10.0.0.5:3000',
  ]);
  const answers: Record<string, string[]> = {
    localhost: ['127.0.0.1', '::1'],
    '127.0.0.2': ['127.0.0.2'],
    '127.1': ['127.0.0.1'],
    'rebound.example': ['::ffff:127.0.0.1'],
    [LAN_ADDRESS]: [LAN_ADDRESS],
    'registry.npmjs.org': ['104.16.0.35'],
  };
  const admit = launcher.admitUnlessStackService(ports, {
    resolve: (host) => {
      const found = answers[host];
      return found === undefined
        ? Promise.reject(new Error(`ENOTFOUND ${host}`))
        : Promise.resolve(found.map((address) => ({ address })));
    },
    localAddresses: [LAN_ADDRESS],
  });

  it('reads the stack’s ports from the loopback entries alone', () => {
    expect([...ports]).toEqual([REDIS_PORT]);
  });

  it('refuses a stack port on every address this machine answers on, and where nothing resolves', async () => {
    for (const host of [
      'localhost',
      '127.0.0.2',
      '127.1',
      'rebound.example',
      LAN_ADDRESS,
      'nowhere.invalid',
    ]) {
      expect(await admit({ host, port: REDIS_PORT }), host).toBe(false);
    }
  });

  it('admits every other loopback port, and the same port elsewhere', async () => {
    expect(await admit({ host: 'localhost', port: 41234 })).toBe(true);
    expect(await admit({ host: '127.0.0.1', port: REDIS_PORT + 1 })).toBe(true);
    expect(await admit({ host: 'registry.npmjs.org', port: REDIS_PORT })).toBe(true);
  });
});

describe('the macOS profile the `open` launcher runs under', () => {
  function shellWord(word: string): string {
    return `'${word.replaceAll("'", `'\\''`)}'`;
  }

  function wrappedBy(command: string): string {
    return wrapCommandWithSandboxMacOS({
      command,
      needsNetworkRestriction: true,
      httpProxyPort: 40001,
      socksProxyPort: 40002,
      allowLocalBinding: true,
      readConfig: { denyOnly: ['/Users/probe'] },
      writeConfig: { allowOnly: ['/tmp/aflow-host'], denyWithinAllow: [] },
    });
  }

  const ports = new Set([REDIS_PORT, STACK_API_PORT_DEFAULT]);

  it('refuses each stack port after the adapter’s loopback grant, and leaves the command as it was', () => {
    const command = ['node', '-e', "console.log('hi')"].map(shellWord).join(' ');
    const wrapped = wrappedBy(command);
    const guarded = launcher.refuseStackServicesInProfile(wrapped, command, ports);
    const grantAt = guarded.indexOf(launcher.LOOPBACK_OUTBOUND_GRANT);
    for (const port of ports) {
      const refusal = `(deny network-outbound (remote ip "localhost:${String(port)}"))`;
      expect(guarded.indexOf(refusal)).toBeGreaterThan(grantAt);
    }
    expect(guarded.length).toBeGreaterThan(wrapped.length);
    expect(guarded.endsWith(wrapped.slice(wrapped.lastIndexOf(" '")))).toBe(true);
  });

  it('is not fooled by a command that spells the grant itself', () => {
    const command = ['echo', launcher.LOOPBACK_OUTBOUND_GRANT].map(shellWord).join(' ');
    const guarded = launcher.refuseStackServicesInProfile(wrappedBy(command), command, ports);
    const profileEnd = guarded.lastIndexOf('echo');
    expect(guarded.indexOf('(deny network-outbound')).toBeLessThan(profileEnd);
  });

  it('refuses to start where the profile does not open loopback as it expects', () => {
    const command = shellWord('true');
    const closed = wrapCommandWithSandboxMacOS({
      command,
      needsNetworkRestriction: true,
      httpProxyPort: 40001,
      socksProxyPort: 40002,
      readConfig: { denyOnly: ['/Users/probe'] },
      writeConfig: { allowOnly: ['/tmp/aflow-host'], denyWithinAllow: [] },
    });
    expect(() => launcher.refuseStackServicesInProfile(closed, command, ports)).toThrow(
      "the stack's own services could not be kept out of reach",
    );
    expect(launcher.refuseStackServicesInProfile(closed, command, new Set())).toBe(closed);
  });
});
